name: CI

on: [push, pull_request]

permissions:
  actions: read
  contents: read
  security-events: write # to fetch code (actions/checkout)

jobs:
  build:
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-${{ matrix.platform }}-${{ matrix.node }}
      cancel-in-progress: true

    strategy:
      fail-fast: false
      matrix:
        node:
          # - '16.14'
          - "18"
          # - '20'
        platform:
          - self-hosted
          # - windows-latest

    name: "${{matrix.platform}} / Node.js ${{ matrix.node }}"
    runs-on: ${{matrix.platform}}

    steps:
      - name: Configure Git
        run: |
          git config --global core.autocrlf false
          git config --global user.name "quangh0409"
          git config --global user.email "trongquangvu80@gmail.com"
      - name: Checkout Commit
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v2.4.0
        with:
          version: next-8
          standalone: true
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: "pnpm"
      - name: Install npm@7
        run: npm add --global npm@7
      - name: pnpm install
        run: pnpm install
      - name: pnpm build
        run: pnpm build
  docker:
    needs: build
    strategy:
      fail-fast: false
      matrix:
        node:
          - "18"
        platform:
          - self-hosted
    name: "${{matrix.platform}} / Node.js ${{ matrix.node }}"
    runs-on: ${{matrix.platform}}

    steps:
      - name: Checkout Commit
        uses: actions/checkout@v4

      - name: stop docker
        run: docker ps -a | awk '$2 ~ /vutrongquang/ {print $1}' | xargs -r docker rm -f

      - name: create .env
        run: |
          cp ./nginx/.env.sample ./nginx/.env
          cp ./apps/auth/.env.sample ./apps/auth/.env
          cp ./apps/file/.env.sample ./apps/file/.env
          cp ./apps/mail/.env.sample ./apps/mail/.env

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and deyloy
        run: docker-compose up -d

      - name: Push
        users: docker/build-push-action@v5
        with:
          push: true
          tags: |
            vutrongquang/gateway
            vutrongquang/file
            vutrongquang/auth
            vutrongquang/mail
