name: CI

on: [push, pull_request]

jobs:
  docker:
    strategy:
      fail-fast: false
      matrix:
        node:
          - "18"
        platform:
          - self-hosted
    name: "Docker"
    runs-on: ${{matrix.platform}}

    steps:
      - name: Checkout Commit
        uses: actions/checkout@v4

      - name: stop docker
        run: docker ps -a | awk '$2 ~ /vutrongquang/ {print $1}' | xargs -r docker rm -f

      - name: create .env
        run: |
          cp ./nginx/.env.sample ./nginx/.env
          cp ./apps/auth/.env.sample ./apps/auth/.env
          cp ./apps/file/.env.sample ./apps/file/.env
          cp ./apps/mail/.env.sample ./apps/mail/.env

      - name: Build and deyloy
        run: docker-compose up -d

      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Push to docker hub
        run: docker-compose push
