name: CI

on: [push, pull_request]

jobs:
  docker:
    strategy:
      fail-fast: false
      matrix:
        node:
          - "18"
        platform:
          - self-hosted
        images:
          - "gateway"
          - "auth"
          - "file"
          - "mail"
    name: "Docker"
    runs-on: ${{matrix.platform}}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push image ${{matrix.images}}
        uses: docker/build-push-action@v5
        with:
          context: .
          build-args: module=${{matrix.images}}
          push: true
          tags: docker.io/vutrongquang/${{matrix.images}}
